### ISSUE TITLE
Add LLVM as alternate backend

### ISSUE THREAD

**Issue by TomBebbington** [TomBebbington/jit.rs#3]
This would be extremely cool as a feature and as a method of evaluating performance differences. LibJIT and LLVM both have similar APIs when it comes to generating IR and because LibJIT's API is pretty minimal, it shouldn't be too hard to give them both the same API. I can imagine LLVM being put in as a feature, so to enable it you just have to use:
``` toml
[dependencies.jit]
version = "*"
features = [ "llvm" ]
```
